### ISSUE TITLE
Update all view settings

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/fast-tracker-tool#25]
export on, set as authoritative, add delete protection, add tags, cache timing set to ___
- [x] All [views](https://airtable.com/appeNORg47YaeETEH/tblm09PfMyLVOa8Of/viwgjJl00VcOXVwvI/fldPFNcHuCHxy0NJi)
  - Tag: "GFT", "Fast Tracker", "Green Fast Track"
  - Share as PUBLIC
  - Mark as Authoritative
  - Turn on Delete Protection
  - Update cache timing (1 hr for all)
  - Toggle on export
 
- [x] All [services](https://airtable.com/appeNORg47YaeETEH/tblm09PfMyLVOa8Of/viwgjJl00VcOXVwvI/fldYpnJhseYUpseJt)
  - Tag: "GFT", "Fast Tracker", "Green Fast Track"
  - Share with OWNER only
  - Mark as Authoritative
  - Turn on Delete Protection
  - Allow Exports

**Comment by caseysmithpgh** [comment]
Above views and services links are seemingly going to the same table--is this intended?
@jackrosacker

**Comment by jackrosacker** [comment]
> Above views and services links are seemingly going to the same table--is this intended? @jackrosacker

Yeah, they link to the two different column headers, but since they're next to each other the destination is basically the same.
