### ISSUE TITLE
"Data Version" dynamic value in report header is broken

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/fast-tracker-tool#29]
Report generated on 10/17/24 has header text that says: 
```
Submitted: October 17, 2024 
Data Version: *
```
But should read:
```
Submitted: October 17, 2024 
Data Version: 24v3*
```

**Comment by caseysmithpgh** [comment]
excel calculation for dcp_mappluto_wi = =CONCAT("pulldata(",CHAR(34),"@layer",CHAR(34),",",CHAR(34),"getValue",CHAR(34),",",CHAR(34),"attributes.v",CHAR(34),",",CHAR(34),"https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/gft_source_data_versions/FeatureServer/54",CHAR(34),",",CHAR(34),"schema_name='",B144, "'", CHAR(34), ")")

When service referenced above is visited in browser, the following occurs: 
<img width="1115" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lGQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44290bb6854d743b17533705a91ebb440ccd9004/image.png" alt="image.png" />

**Comment by caseysmithpgh** [comment]
After further review, it appears that the excel calculation was never updated to reflect v_GFT_Source_Data_Versions. @jackrosacker updated the production survey spreadsheet and the changelog. The subsequent test report submission reflected the appropriate mappluto version. 
<img width="916" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNGQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--716ac89f6ba3b47eee7acce7f9a019d575336ecd/image.png" alt="image.png" />
